// lib/gotore/regions.ts
export type Pref = { code: string; label: string };

export const JP_PREFECTURES: Pref[] = [
  { code: "pref-01", label: "北海道" },
  { code: "pref-02", label: "青森県" },
  { code: "pref-03", label: "岩手県" },
  { code: "pref-04", label: "宮城県" },
  { code: "pref-05", label: "秋田県" },
  { code: "pref-06", label: "山形県" },
  { code: "pref-07", label: "福島県" },
  { code: "pref-08", label: "茨城県" },
  { code: "pref-09", label: "栃木県" },
  { code: "pref-10", label: "群馬県" },
  { code: "pref-11", label: "埼玉県" },
  { code: "pref-12", label: "千葉県" },
  { code: "pref-13", label: "東京都" },
  { code: "pref-14", label: "神奈川県" },
  { code: "pref-15", label: "新潟県" },
  { code: "pref-16", label: "富山県" },
  { code: "pref-17", label: "石川県" },
  { code: "pref-18", label: "福井県" },
  { code: "pref-19", label: "山梨県" },
  { code: "pref-20", label: "長野県" },
  { code: "pref-21", label: "岐阜県" },
  { code: "pref-22", label: "静岡県" },
  { code: "pref-23", label: "愛知県" },
  { code: "pref-24", label: "三重県" },
  { code: "pref-25", label: "滋賀県" },
  { code: "pref-26", label: "京都府" },
  { code: "pref-27", label: "大阪府" },
  { code: "pref-28", label: "兵庫県" },
  { code: "pref-29", label: "奈良県" },
  { code: "pref-30", label: "和歌山県" },
  { code: "pref-31", label: "鳥取県" },
  { code: "pref-32", label: "島根県" },
  { code: "pref-33", label: "岡山県" },
  { code: "pref-34", label: "広島県" },
  { code: "pref-35", label: "山口県" },
  { code: "pref-36", label: "徳島県" },
  { code: "pref-37", label: "香川県" },
  { code: "pref-38", label: "愛媛県" },
  { code: "pref-39", label: "高知県" },
  { code: "pref-40", label: "福岡県" },
  { code: "pref-41", label: "佐賀県" },
  { code: "pref-42", label: "長崎県" },
  { code: "pref-43", label: "熊本県" },
  { code: "pref-44", label: "大分県" },
  { code: "pref-45", label: "宮崎県" },
  { code: "pref-46", label: "鹿児島県" },
  { code: "pref-47", label: "沖縄県" },
];

// キー：バリエーション（reverseGeocode の administrativeArea で来る文字など）   label
const PREF_NAME_MAP: Record<string, string> = {
  "東京都": "東京都", "tokyo": "東京都",
  "大阪府": "大阪府", "osaka": "大阪府",
  "神奈川県": "神奈川県", "kanagawa": "神奈川県",
  "千葉県": "千葉県", "chiba": "千葉県",
  "埼玉県": "埼玉県", "saitama": "埼玉県",
  "愛知県": "愛知県", "aichi": "愛知県",
  "北海道": "北海道", "hokkaido": "北海道",
  "福岡県": "福岡県", "fukuoka": "福岡県",
  "兵庫県": "兵庫県", "hyogo": "兵庫県",
  "京都府": "京都府", "kyoto": "京都府",
  "静岡県": "静岡県", "shizuoka": "静岡県",
  "茨城県": "茨城県", "ibaraki": "茨城県",
  "栃木県": "栃木県", "tochigi": "栃木県",
  "群馬県": "群馬県", "gunma": "群馬県",
  "新潟県": "新潟県", "niigata": "新潟県",
  "富山県": "富山県", "toyama": "富山県",
  "石川県": "石川県", "ishikawa": "石川県",
  "福井県": "福井県", "fukui": "福井県",
  "山梨県": "山梨県", "yamanashi": "山梨県",
  "長野県": "長野県", "nagano": "長野県",
  "岐阜県": "岐阜県", "gifu": "岐阜県",
  "三重県": "三重県", "mie": "三重県",
  "滋賀県": "滋賀県", "shiga": "滋賀県",
  "奈良県": "奈良県", "nara": "奈良県",
  "和歌山県": "和歌山県", "wakayama": "和歌山県",
  "鳥取県": "鳥取県", "tottori": "鳥取県",
  "島根県": "島根県", "shimane": "島根県",
  "岡山県": "岡山県", "okayama": "岡山県",
  "広島県": "広島県", "hiroshima": "広島県",
  "山口県": "山口県", "yamaguchi": "山口県",
  "徳島県": "徳島県", "tokushima": "徳島県",
  "香川県": "香川県", "kagawa": "香川県",
  "愛媛県": "愛媛県", "ehime": "愛媛県",
  "高知県": "高知県", "kochi": "高知県",
  "佐賀県": "佐賀県", "saga": "佐賀県",
  "長崎県": "長崎県", "nagasaki": "長崎県",
  "熊本県": "熊本県", "kumamoto": "熊本県",
  "大分県": "大分県", "oita": "大分県",
  "宮崎県": "宮崎県", "miyazaki": "宮崎県",
  "鹿児島県": "鹿児島県", "kagoshima": "鹿児島県",
  "沖縄県": "沖縄県", "okinawa": "沖縄県",
  "宮城県": "宮城県", "miyagi": "宮城県",
  "秋田県": "秋田県", "akita": "秋田県",
  "山形県": "山形県", "yamagata": "山形県",
  "福島県": "福島県", "fukushima": "福島県",
  "青森県": "青森県", "aomori": "青森県",
  "岩手県": "岩手県", "iwate": "岩手県",
};

export function findPrefByName(input: string): Pref | null {
  if (!input) return null;
  const key = input.trim().toLowerCase();
  const label = PREF_NAME_MAP[input] || PREF_NAME_MAP[key];
  if (!label) return null;
  const pref = JP_PREFECTURES.find(p => p.label === label) || null;
  return pref || null;
}
